export default function ExecutiveTemplate({ resume }) {
    const skills = (resume.skills || "").spit(",").filter(skill => skill.trim());
    return (
        <div className="bg-white shadow-2xl max-w-5xl mx-auto border">
           
           <div className="bg-gray-900 text-white p-10">

            <h1 className="text-5xl font-bold tracking-wide">
                {res8me.fullName || "Your Name" }
            </h1>

            <p className="text-2xl text-yellow-400 mt-3">
                {resume.targetRole || "Executive" }
            </p>

            <div className="flex gap-8 mt-5 text-gray-300">

                <span>{resume.email}</span>

                <span>{resume.photo}</span>

            </div>

           </div>

           <div className="p-10 space-y-10">

            <section>

                <h2 className="text-2xl font-bold text-yellow-600 border-b-2 border-yellow-500 pb-2">
                    Executive Summary
                </h2>

                <p className="mt-5 leading-8 whitespace-pre-wrap text-gray-700">
                    {resume.summary || "Professional Summary" }
                </p>

            </section>

            <section>

                <h2 className="text-2xl font-bold text-yellow-600 border-b-2 border-yellow-500 pb-2">
                    Major Projects
                </h2>

                <p className="mt-5 leading-8 whitespace-pre-wrap text-gray-700">
                    {resume.projects || "Projects" }
                </p>
                 
            </section>

            <section>

                <h2 className="text-2xl font-bold text-yellow-600 border-b-2 border-yellow-500 pb-2">
                    Core Competencies
                </h2>

                <div className="flex flex-wrap gap-3 mt-5">

                    {skills.map((skill, index) => (
                        <span key={index} className="bg-gray-900 text-yellow-400 px-4py-2 rounded-full font-medium">
                            {skill.trim()}
                        </span>
                    ))}
                </div>
            </section>

            <section>
                
                <h2 className="text-2xl font-bold text-yellow-600 border-b-2 border-yellow-500 pb-2">
                    Education
                </h2>

                <p className="mt-5 leading-8 whitespace-pre-wrap text-gray-700">
                    {resume.education || "Education" }
                </p>

            </section>

            <div className="text-center text-gray-400 text-sm pt-8">
                Generated by Career Compass AI
            </div>
           </div>
        </div>
    );
}