export default function ModernTemplate({ resume }) {
    return (
        <>
            <div className="bg-white shadow-xl rounded-xl p-10 max-w-4xl mx-auto border">

                <h1 className="text-5xl font-extrabold text-blue-700">
                    {resume.fullName || "Your Name"}
                </h1>

                <p className="text-xl text-gray-600 mt-2">
                    {resume.targetRole || "Target Role"}
                </p>

                <div className="flex flex-wrap gap-5 text-gray-500 text-sm mt-4">
                    <span>
                        {resume.email}
                    </span>
                    <span>
                        {resume.phone}
                    </span>
                    {resume.linkedin && (
                        <span>{resume.linkedin}</span>
                    )}
                    {(resume.github && (<span>
                        {resume.github}
                    </span>
                    ))}
                    {(resume.portfolio && (<span>
                        {resume.portfolio}
                        </span>
                    ))
                }
                </div>

                <hr className="my-5" />

                <h2 className="text-2xl font-bold text-blue-700 mt-8 pb-2 border-b-2 border-blue-200">
                    Summary
                </h2>

                <p className="whitespaces-pre-wrap leading-7 text-gray-700">
                    {resume.summary || "Your Professional Summary"}
                </p>

                <hr className="my-5" />

                <h2 className="font-bold text-2xl text-blue-700 mt-8 pb-2 border-b-2 border-blue-200">
                    Education
                </h2>

                <p>
                    {resume.education || "Education Details"}
                </p>
                
                <hr className="my-5" />

                <h2 className="font-bold text-2xl text-blue-700 mt-8 pb-2 border-b-2 border-blue-200">
                    Experience
                </h2>

                <p>
                    {resume.experience || "Work Experience"}
                </p>

                <hr className="my-5" />

                <h2 className="font-bold text-2xl text-blue-700 mt-8 pb-2 border-b-2 b order-blue-200">
                    Skills
                </h2>

                <div className="flex flex-wrap gap-3 mt-3">
                    {(resume.skills || "")
                    .split(",")
                    .filter(skill => skill.trim())
                    .map((skill, index) => (
                        <span key={index} 
                        className="bg-blue-100 text-blue-700 px-4 py-2 rounded-full text-sm">
                            {skill.trim()}
                        </span>
                    ))}
                </div>

                <hr className="my-5" />

                <h2 className="font-bold text-2xl text-blue-700 mt-8 pb-2 border-b-2 border-blue-200">
                    Projects
                </h2>

                <p>
                    {resume.projects || "Projects"}
                </p>

            </div>
            <div className="text-center mt-16 text-xs text-gray-400">
                Generated by Career Compass AI
            </div>
        </>

    );

}