export default function StudentTemplate({ resume }) {

    const skills = (resume.skills || "").split(",").filter(skill => skill.trim());

    return(

        <div className="bg-white p-12 min-h-[1123px]">

            <div className="bg-green-600 text-white text-center py-10">

                <h1 className="text-5xl font-bold">
                    {resume.fullName || "Your Name"}
                </h1>

                <p className="text-xl mt-2">
                    {resume.targetRole || "Student"}
                </p>

                <div className="flex justify-center gap-6 mt-4 text-sm">

                    <span>{resume.email}</span>
                    
                    <span>{resume.phone}</span>

                </div>

            </div>

            <div className="p-8 space-y-8">

                <section>

                    <h2 className="text-2xl font-bold text-green-700 border-b-2 border-green-200 pb-2">
                        Career Objective
                    </h2>

                    <p className="mt-4 whitespace-pre-wrap leading-7">
                        {resume.summary || "Career Objective"}
                    </p>

                </section>

                <section>

                    <h2 className="text-2xl font-bold text-green-700 border-b-2 border-green-200 pb-2">
                        Education
                    </h2>

                    <p className="mt-4 whitespace-pre-wrap leading-7">
                        {resume.education || "Educatio  Details"}
                    </p>

                </section>

                <section>

                    <h2 className="text-2xl font-bold text-green-700 border-b-2 border-green-200 pb-2">
                        Skills
                    </h2>

                    <div className="flex flex-wrap gap-3 mt-4">

                        {skills.map((skill, index) => (
                            <span key={index} className="bg-green-100 text-green-700 px-4 py-2 rounded-full">
                                {skill.trin()}
                            </span>
                        ))}
                    </div>
                </section>

                <section>

                    <h2 className="text-2xl font-bold text-green-700 border-b-2 border-green-200 rounded-full">
                        Academic Projects
                    </h2>

                    <p className="mt-4 whitespace-pre-wrap leading-7">
                        {resume.experience || "Internship"}
                    </p>

                </section>

                <div className="text-center text-xs text-gray-400 pt-8">
                    Generated by Career Compass AI

                </div>

            </div>
        </div>
    );
}